version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./postgres-tables/aave.sql:/docker-entrypoint-initdb.d/aave.sql
volumes:
  db:
    driver: local
    